Node pr
smartlearnjbl/smartLearnNodeJs pull request #6
Opened 2023-05-04 07:07 UTC by parth-jainam

2023-05-04 11:16 UTC, allstuffrj requested changes

2023-05-04 11:16 UTC, allstuffrj commented on controller/course/courseServiceController.js
> +                  WHERE course_languages.language_id = ${language_id} AND courses.mentor_id = ${mentor_id} AND courses.deleted = 'false'`
why there is false in string?

2023-05-04 11:17 UTC, allstuffrj requested changes

2023-05-04 11:17 UTC, allstuffrj commented on services/courseService/course.js
> +      AND course_status = 'enabled' AND deleted = 'false'`
why boolean value in string?

2023-05-04 11:17 UTC, allstuffrj commented on services/courseService/course.js
> +      `SELECT * FROM courses WHERE id = ${req.params.course_id} AND deleted = 'false'`
same here

2023-05-04 11:17 UTC, allstuffrj commented on services/courseService/course.js
> +      `SELECT * FROM courses WHERE id = ${req.params.id} AND deleted = 'false'`
same here

2023-05-04 11:17 UTC, allstuffrj commented on services/courseService/course.js
> +      `SELECT * FROM courses WHERE id = ${req.params.course_id} AND deleted = 'false'`
same here

2023-05-04 11:17 UTC, allstuffrj commented on services/courseService/course.js
> +    await db.query(`UPDATE courses SET deleted = 'true' WHERE id = ${req.params.id}`);
same here

2023-05-04 11:17 UTC, allstuffrj commented on services/courseService/course.js
> +      `UPDATE course_languages SET deleted = 'true' WHERE course_id = ${req.params.id}`
same here

2023-05-04 11:20 UTC, allstuffrj requested changes

2023-05-04 11:20 UTC, allstuffrj commented on migrations/20230131080747-create-course.js
> +        type:Sequelize.BOOLEAN
What will be the default value for deleted?

2023-05-04 11:39 UTC, parth-jainam commented on migrations/20230131080747-create-course.js
> +        type:Sequelize.BOOLEAN
not set yet i will push it.

2023-05-04 11:42 UTC, parth-jainam commented on controller/course/courseServiceController.js
> +                  WHERE course_languages.language_id = ${language_id} AND courses.mentor_id = ${mentor_id} AND courses.deleted = 'false'`
i will change this to boolean type

2023-05-04 11:42 UTC, parth-jainam commented on services/courseService/course.js
> +      AND course_status = 'enabled' AND deleted = 'false'`
i will change this to boolean type

2023-05-04 11:43 UTC, parth-jainam commented on services/courseService/course.js
> +    let allCourse = await db.query(`SELECT * FROM courses where deleted = 'false'`);
i will change this to boolean type

2023-05-04 11:44 UTC, parth-jainam commented on migrations/20230131080747-create-course.js
> +        type:Sequelize.BOOLEAN
not set yet,after set i will push it.

2023-05-04 12:19 UTC, parth-jainam commented on services/userService/userMail.js
> +    var random_string = (Math.random() + 1).toString(36).substring(7);
sir i try to implement bcrypt but bcrypt return hash with / .because of that path not found so i use this way to create string.

2023-05-05 04:50 UTC, allstuffrj approved these changes
LGTM

2023-05-05 04:50 UTC, merged